= Quality Manual, Policy and Objectives
:toc: auto

== Summary

The Quality Manual describes the scope of the Quality Management System (QMS),
its documented procedures and a description of their interactions.

== 1. Scope

The QMS described in this Quality Manual applies to all software products of https://github.com/openehr4j[openEHR 4J].

=== Role of Project

include::role-of-project/index.adoc[]

== 2. Quality Policy & Objectives

include::quality-policy/index.adoc[]

=== Quality Objectives

____
Whatever policy you outlined above, now you need to make it measurable
by defining objectives which can be tracked. Those objectives should not
(only) refer to the quality of your devices but the quality of your QMS
and the overall work of your organization. Typical examples are: hiring
excellence in staff, providing, best-of-class device performance, high
standards of customer satisfaction, etc.
____

=== Key Performance Indicators (KPIs)

____
Auditors might ask you: how do you keep track of a quality objective, to
see if it was achieved or not? The answer is: Key Performance
Indicators. As part of your management review, you have to review all
QMS processes plus your quality policy and objectives at least annually.
Now, you can meet both requirements at the same time by defining KPIs
for your QMS processes. You can then argue that by achieving your KPIs,
you make sure that your processes run well, which also meets your
quality objectives.
____

____
These are your action items: 1. Make sure to define at least one KPI for
each QMS process. 2. Make sure each quality objectives translates into
at minimum one process KPI. Where there’s no corresponding process for a
quality objective, you define additional KPIs that are not
process-related. 3. You can document those KPIs either in each SOP or in
a separate overview sheet. For example, you can use the template for a
management review report for that purpose.

Also see regulatory requirements: ISO 13485, para. 4.1.3.a (process
KPIs) and para. 5.6.2 (management review input).

In this section here, describe where you define your KPIs and how you
keep track of them. For example, say that you define KPIs in every
single SOP or reference to a separate, central overview sheet. Ideally,
KPIs are tracked by each process owner independently.
____

== 3. Roles

____
Describe the roles of the people in your company. Typically this is done
by drawing an organigram (you could use draw.io for that). Or, you just
use a table like below.

Minimum requirement information: required qualification and description
of tasks related to QMS process involvement If applicable, add: report /
authority, access rights, etc.
____

[cols=",",options="header",]
|===
|Role |People
|CEO |Steve Jobs
|CTO |Steve Wozniak
|Product Manager |Ada Lovelace
|QMO |Oliver Eidel
|===

All C-level roles (CEO, CTO, CMO) are referred to as the Management.
Management is generally responsible to define responsibilities and
authorities, to define and communicate Quality Policy and Goals and to
ensure that the whole organization is oriented towards them.

____
See ISO 13485, para. 5.1, para. 5.5.1
____

The Quality Management Officer (QMO) is responsible for:

* ensuring that processes needed for the company’s quality management
system are documented
* reporting to top management on the effectiveness of the quality
management system and any need for improvement
* ensuring the promotion of awareness of applicable regulatory
requirements and QMS requirements throughout the organization.

Required qualification for this role:

* Fluent in German and English language
* At minimum one year of professional experience in the fields of
quality management and regulatory affairs

____
See ISO 13485, para. 5.1, para. 5.5.2
____

Person Responsible for Regulatory Compliance (PRRC) Responsibilities of
the PRRC are in accordance with Art. 15 MDR as follows:

* Ensure (review / release) the conformity of the devices is
appropriately checked in accordance with the QMS before a device is
released (also see Art. 10 Para. 9 MDR)
* Ensure (review / release) that the technical documentation and the EU
declaration of conformity are drawn up and kept up-to-date for all
medical devices (also see Art. 10 Para. 4 and Art. 6 MDR)
* Ensure (review / release) that obligations for post-market
surveillance are complied with in accordance with Art. 10 Para. 10 MDR
* Ensure (review / release) that the reporting obligations of Articles
87 to 91 MDR are fulfilled (FSCA / incidents, also see Art. 10 Para. 13
MDR)
* Ensure that, in the case of investigational devices, the statement
referred to in Section 4.1 of Chapter II of Annex XV MDR is issued.

The PRRC shall not be subjected to Management instructions while
carrying out his/her responsibilities specified above. His/her tasks may
be delegated to other roles as long as it is ensured that final
responsibility stays with the PRRC. She or he has the power and
authority to represent the company in the scope of his/her
responsibilities, e.g. in communicating with state authorities.

Required qualification for this role:

* Fluent in English language
* Knowledge of the role and responsibilities of a '`Person Responsible
for Regulatory Compliance`' according to Art. 15 MDR
* Higher education degree in law, medicine, pharmacology or engineering
** OR: four years of professional experience in the fields of quality
management and regulatory affairs
* At minimum one year of professional experience in the fields of
quality management and regulatory affairs

== 4. Processes

____
List all your SOPs here. This list is highly company-specific and might
therefore be currently incomplete.

*Important Note:*

Also mention if one of these processes is outsourced to a third party
(typical examples: internal auditing or clinical evaluation done by a
regulatory consultant, software development done by an external agency;
see ISO 13485:2016, para. 4.1.5 for more context).
____

[width="100%",cols="52%,21%,27%",options="header",]
|===
|SOP |Process Category |Internal / Outsourced
|SOP Corrective and Preventive Action |Management |Internal
|SOP Clinical Evaluation |Core |Outsourced (?)
|SOP Product Certification and Registration |Core |Internal
|SOP Change Management |Core |Internal
|SOP Deployment |Core |Internal
|SOP Document and Record Control |Support |Internal
|SOP Integrated Software Development |Core |Internal
|SOP Feedback Management |Core |Internal
|SOP Internal Auditing |Management |Outsourced (?)
|SOP Management Review |Management |Internal
|SOP Post-Market Surveillance |Management |Internal
|SOP Problem Resolution |Core |Internal
|SOP Software Validation |Support |Internal
|SOP Update of Regulations |Support |Internal
|SOP Vigilance |Core |Internal
|===

'''''


[[glossary]]
== Glossary

[glossary]

SDK:: Software Development Kit. A package developed by a third party that can be used within the source code of the source code of a software product.

[discrete]
== Legal notice

Template Copyright https://openregulatory.com[openregulatory.com]. See
https://openregulatory.com/template-license[template license].

Please don’t remove this notice even if you’ve modified contents of this
template.
