name: Publish
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: "Add git configuration"
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-action-bot@experimental-software.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Build and publish
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          ./.github/scripts/publish_gh_pages.sh -v ${TAG_NAME}
